onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - gatsby
  - gatsby-cli
  - lmdb
  - msgpackr-extract
  - sharp
  - spawn-sync
